### ISSUE TITLE
module 'em' has no attribute 'RAW_OPT'

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/Prometheus#1]
```
Traceback (most recent call last):
  File "tools/px_generate_uorb_topic_files.py", line 530, in <module>
    generate_idx, f, args.temporarydir, args.package, args.templatedir, INCL_DEFAULT)
  File "tools/px_generate_uorb_topic_files.py", line 177, in generate_output_from_file
    return generate_by_template(output_file, template_file, em_globals)
  File "tools/px_generate_uorb_topic_files.py", line 346, in generate_by_template
    em.RAW_OPT: True, em.BUFFERED_OPT: True})
AttributeError: module 'em' has no attribute 'RAW_OPT'
[9/812] Generating serial_params.c
ninja: build stopped: subcommand failed.
Makefile:224: recipe for target 'amovlab_sitl_default' failed
make: *** [amovlab_sitl_default] Error 1
```

**Comment by HuaYuXiao** [comment]
```bash
pip3 uninstall em
pip3 install empy==3.3.4
```

Reference:
- https://stackoverflow.com/questions/77642155/attributeerror-module-object-has-no-attribute-raw-opt/77656642#77656642
