### ISSUE TITLE
load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/Prometheus#3]
```
----------------------------------------------------------------------
WARNING: Your workspace is not extending any other result space, but
it is set to use a `linked` devel space layout. This requires the
`catkin` CMake package in your source space in order to be built.
----------------------------------------------------------------------

Error: There already is a workspace config file .rosinstall at "src". Use wstool install/modify.
Traceback (most recent call last):
  File "/usr/bin/wstool", line 62, in <module>
    sys.exit(wstool.wstool_cli.wstool_main(sys.argv))
  File "/usr/lib/python3/dist-packages/wstool/wstool_cli.py", line 180, in wstool_main
    return ws_commands[command](workspace, args)
  File "/usr/lib/python3/dist-packages/wstool/multiproject_cli.py", line 584, in cmd_merge
    allow_other_element=self.allow_other_element)
  File "/usr/lib/python3/dist-packages/wstool/multiproject_cli.py", line 200, in prompt_merge
    config_filename=config_filename)
  File "/usr/lib/python3/dist-packages/wstool/multiproject_cmd.py", line 101, in get_config
    as_is=True)
  File "/usr/lib/python3/dist-packages/wstool/config_yaml.py", line 110, in get_path_specs_from_uri
    yaml_spec = get_yaml_from_uri(uri)
  File "/usr/lib/python3/dist-packages/wstool/config_yaml.py", line 74, in get_yaml_from_uri
    yamldata = yaml.load(stream)
TypeError: load() missing 1 required positional argument: 'Loader'
```

**Comment by HuaYuXiao** [comment]
```bash
pip install wstool
```
